### ISSUE TITLE
Persistencia de entidad Transaccion

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p3_g3_sf#37]
**Descripción:** Crear los siguientes archivos para la entidad `Transaccion`:

* `TransaccionRepository.java`
* `ITransaccionService.java`
* `TransaccionServiceImpl.java`
* `TransaccionController.java`

En el servicio, desarrollar los métodos:

* `getAll()`
* `getById(Long id)`
* `save(Transaccion transaccion)`
* `delete(Long id)`
* `exists(Long id)`

En el controlador, crear los endpoints para las llamadas `GET`, `POST`, `PUT` y `DELETE`.

**Ejemplo de la Interfaz (ITransaccionService.java):**

```java
    public interface ITransaccionService {
        List<Transaccion> getAll();
        Transaccion getById(Long id);
        Transaccion save(Transaccion transaccion);
        void delete(Long id);
        boolean exists(Long id);
    }
```

**Instrucciones adicionales:** Adjuntar capturas de todas las llamadas a los métodos a través de PostMan en el pull request.

**Comment by AnaMaco** [comment]
Profe espereme que tengo que hacer arreglos.
