### ISSUE TITLE
Crear endpoint para actualizar la descripción de una ubicación

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p3_g3_sf#71]
### **Descripción:**
Añadir un nuevo endpoint en el controlador de ubicaciones que permita actualizar únicamente la descripción de una ubicación existente utilizando una petición HTTP `PUT`. Esto facilitará la modificación de la descripción sin tener que enviar toda la información de la ubicación.

### **Tareas a realizar:**

1. **Crear el endpoint en el `UbicacionController`:**
   - Desarrollar un nuevo método `updateDescripcion` que maneje solicitudes `PUT` al endpoint `/api/ubicaciones/{id}/descripcion`.
   - El método debe recibir el ID de la ubicación en la URL y un cuerpo JSON que contenga la nueva descripción.

2. **Modificar el servicio de ubicaciones:**
   - Añadir un método en el servicio `IUbicacionService` para actualizar solo la descripción de una ubicación.
   - Validar que la ubicación existe antes de realizar la actualización.

3. **Validaciones:**
   - Si el ID de la ubicación no existe, devolver un mensaje de error adecuado.
   - Si no se envía una descripción o es inválida (vacía, etc.), devolver un mensaje de error indicando que se requiere una descripción válida.

4. **Pruebas del endpoint:**
   - Utilizar Postman para probar el nuevo endpoint con diferentes ubicaciones y descripciones.
   - Asegurarse de que se manejen correctamente los casos de éxito y error, como una ubicación inexistente o una descripción no válida.

5. **Documentación:**
   - Actualizar la documentación de la API para incluir el nuevo endpoint `/api/ubicaciones/{id}/descripcion`, detallando el parámetro de entrada (`descripcion`), su formato esperado, y las posibles respuestas.

### **Criterios de aceptación:**
- El endpoint debe permitir actualizar únicamente la descripción de la ubicación especificada.
- El método debe manejar adecuadamente los errores, como una ubicación inexistente o una descripción no válida.
- El código debe seguir las mejores prácticas de desarrollo en Spring Boot.

**Comment by Animartix** [comment]
![image](https://github.com/user-attachments/assets/d686d99d-f9a4-488c-a401-40f228015399)
![image](https://github.com/user-attachments/assets/5a8a1a4a-2b38-4d48-9ff4-175e5a72d7e1)
![image](https://github.com/user-attachments/assets/f1d5dd9b-39de-44ed-a273-8520f8b8304c)
![image](https://github.com/user-attachments/assets/e48a8db0-1ae8-40f4-9eb6-347b23e5cf28)
